---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Deploy early (foundation)
spec:
  project: platform

  source:
    repoURL: git@github.com:TrungHQ-02/kubernetes-extreme-lab.git
    targetRevision: main
    path: platform/core/cert-manager
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: false 
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health assessment
  health:
    startupProbe:
      initialDelaySeconds: 10
      periodSeconds: 10
