# Ansible Inventory - Generated by Terraform
# Cluster: ${cluster_name}
# Environment: ${environment}

[k3s_cluster]
localhost ansible_connection=local

[k3s_masters]
localhost ansible_connection=local

[k3s_cluster:vars]
k3s_version=${k3s_version}
cluster_name=${cluster_name}
environment=${environment}
pod_cidr=${pod_cidr}
service_cidr=${service_cidr}
ansible_python_interpreter=/usr/bin/python3
