---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "11"  # After demo-app
    notifications.argoproj.io/subscribe.on-deployed.slack: "platform-deployments"
    notifications.argoproj.io/subscribe.on-health-degraded.slack: "platform-alerts"
spec:
  project: applications

  source:
    repoURL: git@github.com:fsongt-ext/kubernetes-extreme-lab.git
    targetRevision: main
    path: helm/microservices-demo
    helm:
      valueFiles:
        - values.yaml
        - values-lab.yaml  # Lab environment overrides

  destination:
    server: https://kubernetes.default.svc
    namespace: boutique

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health assessment
  info:
    - name: 'Application'
      value: 'Online Boutique - Microservices Demo'
    - name: 'Environment'
      value: 'lab'
    - name: 'Services'
      value: '11 microservices'
