---
##############################################################################
# Argo CD AppProject - Platform Components
#
# Defines RBAC, allowed resources, and policies for platform team
##############################################################################

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Platform components managed by Platform Team

  # Source repositories allowed
  sourceRepos:
    - 'https://github.com/yourusername/kubernetes-extreme-lab'
    - 'https://charts.jetstack.io'
    - 'https://istio-release.storage.googleapis.com/charts'
    - 'https://charts.konghq.com'
    - 'https://grafana.github.io/helm-charts'
    - 'https://argoproj.github.io/argo-helm'
    - 'https://open-policy-agent.github.io/gatekeeper/charts'
    - 'https://kyverno.github.io/kyverno'

  # Destination clusters and namespaces
  destinations:
    - namespace: 'argocd'
      server: https://kubernetes.default.svc
    - namespace: 'cert-manager'
      server: https://kubernetes.default.svc
    - namespace: 'istio-system'
      server: https://kubernetes.default.svc
    - namespace: 'kong'
      server: https://kubernetes.default.svc
    - namespace: 'gatekeeper-system'
      server: https://kubernetes.default.svc
    - namespace: 'kyverno'
      server: https://kubernetes.default.svc
    - namespace: 'observability'
      server: https://kubernetes.default.svc
    - namespace: 'argo-rollouts'
      server: https://kubernetes.default.svc
    - namespace: 'velero'
      server: https://kubernetes.default.svc

  # Cluster resource whitelist
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: ''
      kind: Node
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: 'apiextensions.k8s.io'
      kind: CustomResourceDefinition
    - group: 'admissionregistration.k8s.io'
      kind: MutatingWebhookConfiguration
    - group: 'admissionregistration.k8s.io'
      kind: ValidatingWebhookConfiguration
    - group: 'cert-manager.io'
      kind: ClusterIssuer
    - group: 'networking.istio.io'
      kind: Gateway
    - group: 'kyverno.io'
      kind: ClusterPolicy
    - group: 'templates.gatekeeper.sh'
      kind: ConstraintTemplate

  # Namespace resource whitelist (all allowed)
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  # Sync windows (optional maintenance windows)
  syncWindows:
    - kind: allow
      schedule: '* * * * *'
      duration: 24h
      applications:
        - '*'
      manualSync: true

  # Orphaned resources monitoring
  orphanedResources:
    warn: true
