##############################################################################
# Terraform Outputs - Lab Environment
##############################################################################

output "ssh_command" {
  description = "SSH command to connect to the VM"
  value       = "ssh ${module.vm.admin_username}@${module.vm.public_ip_address}"
}

output "auth_admin_secret" {
  description = "az cli command to get secret from keyvault"
  value       = "az keyvault secret show --name KC-BOOTSTRAP-ADMIN-PASSWORD --vault-name ${values(module.keyvaults)[0].key_vault_name} --query value -o tsv"
}

output "dns_records" {
  description = "DNS A records created"
  value       = module.dns.a_record_fqdns
}

output "acr_login_server" {
  description = "ACR login server URL"
  value       = module.acr.login_server
}

output "acr_admin_username" {
  description = "az cli command to get ACR admin username from Key Vault"
  value       = "az keyvault secret show --name ACR-ADMIN-USERNAME --vault-name ${values(module.keyvaults)[0].key_vault_name} --query value -o tsv"
}

output "acr_admin_password" {
  description = "az cli command to get ACR admin password from Key Vault"
  value       = "az keyvault secret show --name ACR-ADMIN-PASSWORD --vault-name ${values(module.keyvaults)[0].key_vault_name} --query value -o tsv"
}

output "acr_docker_login" {
  description = "Docker login command for ACR using Key Vault credentials"
  value       = "docker login ${module.acr.login_server} -u $(az keyvault secret show --name ACR-ADMIN-USERNAME --vault-name ${values(module.keyvaults)[0].key_vault_name} --query value -o tsv) -p $(az keyvault secret show --name ACR-ADMIN-PASSWORD --vault-name ${values(module.keyvaults)[0].key_vault_name} --query value -o tsv)"
}



##############################################################################
# Configuration Files - Generated by Terraform
##############################################################################

# Caddyfile Configuration
resource "local_file" "caddyfile" {
  filename = "${path.module}/../../../ansible/roles/caddy/templates/Caddyfile"
  content  = <<-EOF
# Caddyfile - Automatic HTTPS Reverse Proxy
# Generated by Terraform

# Keycloak with automatic HTTPS
auth.${local.domain} {
    reverse_proxy localhost:8080 {
        header_up X-Forwarded-Host {host}
        header_up X-Forwarded-Proto {scheme}
        header_up X-Forwarded-For {remote}
    }
    
    # Enable access logs
    log {
        output file /var/log/caddy/access.log
    }
}
EOF

  file_permission = "0644"
}

# Keycloak systemd service
resource "local_file" "keycloak_service" {
  filename = "${path.module}/../../../ansible/roles/keycloak/templates/keycloak.service"
  content  = <<-EOF
[Unit]
Description=Keycloak Application Server
After=network.target

[Service]
Type=simple
User=keycloak
Group=keycloak

Environment="KC_BOOTSTRAP_ADMIN_USERNAME=admin"
Environment="KC_BOOTSTRAP_ADMIN_PASSWORD_SECRET=${values(module.keyvaults)[0].key_vault_name}/KC-BOOTSTRAP-ADMIN-PASSWORD"
Environment="KC_HTTP_PORT=8080"
Environment="KC_HOSTNAME=auth.${local.domain}"
Environment="KC_PROXY_HEADERS=xforwarded"

# Fetch password from Key Vault at runtime
ExecStartPre=/bin/bash -c 'export KC_BOOTSTRAP_ADMIN_PASSWORD=$$(az keyvault secret show --vault-name ${values(module.keyvaults)[0].key_vault_name} --name KC-BOOTSTRAP-ADMIN-PASSWORD --query value -o tsv)'

ExecStart=/opt/keycloak/bin/kc.sh start-dev --http-enabled=true --proxy-headers=xforwarded --hostname-strict=false

Restart=on-failure
RestartSec=10

StandardOutput=journal
StandardError=journal
SyslogIdentifier=keycloak

[Install]
WantedBy=multi-user.target
EOF

  file_permission = "0644"
}

# K3s Configuration
resource "local_file" "k3s_config" {
  filename = "${path.module}/../../../ansible/roles/k3s/templates/k3s-config.yaml"
  content  = <<-EOF
# K3s Configuration File
# Generated by Terraform

# Network Configuration
cluster-cidr: "${local.network.pod_cidr}"
service-cidr: "${local.network.service_cidr}"
cluster-dns: "${local.network.cluster_dns}"

# Disable default components (we'll install our own)
disable:
  - traefik
  - servicelb
  - local-storage

# Kubeconfig
write-kubeconfig-mode: "0644"
write-kubeconfig: /etc/rancher/k3s/k3s.yaml

# Security - Secrets Encryption
secrets-encryption: true

# Security - Kernel Defaults
protect-kernel-defaults: false  # Set to true for production

# API Server Arguments
kube-apiserver-arg:
  - "audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log"
  - "audit-log-maxage=30"
  - "audit-log-maxbackup=10"
  - "audit-log-maxsize=100"
  - "anonymous-auth=false"
  - "enable-admission-plugins=NodeRestriction"

# Controller Manager Arguments
kube-controller-manager-arg:
  - "terminated-pod-gc-threshold=10"

# Kubelet Arguments
kubelet-arg:
  - "max-pods=110"
  - "eviction-hard=memory.available<500Mi,nodefs.available<10%"
  - "eviction-soft=memory.available<1Gi,nodefs.available<15%"
  - "eviction-soft-grace-period=memory.available=1m30s,nodefs.available=2m"

# Flannel Backend
flannel-backend: ${local.k3s_config.flannel-backend}

# Disable components (using our own)
disable-cloud-controller: true
disable-network-policy: false

# TLS SANs - Add public IP for external access
tls-san:
  - "${module.vm.public_ip_address}"
EOF

  file_permission = "0644"
}

# Ansible inventory file
resource "local_file" "ansible_inventory" {
  filename = "${path.module}/../../../ansible/inventory/lab.ini"
  content  = <<-EOF
[k3s_cluster]
${module.vm.public_ip_address} ansible_host=${module.vm.public_ip_address} ansible_user=${module.vm.admin_username}

[k3s_cluster:vars]
# Key Vault configuration
keyvault_name=${values(module.keyvaults)[0].key_vault_name}

# Domain configuration
caddy_domain=auth.${local.domain}
caddy_backend_port=8080

# Keycloak configuration
keycloak_version=${local.keycloak_version}
keycloak_download_url=https://github.com/keycloak/keycloak/releases/download/${local.keycloak_version}/keycloak-${local.keycloak_version}.tar.gz

# K3s configuration
k3s_version=${local.k3s_version}
k3s_config_dir=/etc/rancher/k3s
pod_cidr=${local.network.pod_cidr}
service_cidr=${local.network.service_cidr}
cluster_dns=${local.network.cluster_dns}
EOF

  file_permission = "0644"
}

output "generated_configs" {
  description = "Paths to generated configuration files"
  value = {
    caddyfile         = local_file.caddyfile.filename
    keycloak_service  = local_file.keycloak_service.filename
    k3s_config        = local_file.k3s_config.filename
    ansible_inventory = local_file.ansible_inventory.filename
  }
}
